export const SET_NOTIFICATIONS = "[NOTIFICATIONS] SET_NOTIFICATIONS";
export const ADD_NOTIFICATION = "[NOTIFICATIONS] ADD_NOTIFICATION";
export const SET_NOTIFICATION_BY_TENANT = "[NOTIFICATIONS] ADD_NOTIFICATION_BY_TENANT";
export const SWITCH_BOOLEAN_GET_NOTIFICATION = "[NOTIFICATIONS] SWITCH_BOOLEAN_GET_NOTIFICATION";
export const SWITCH_STATE_NOTIFICATION_BY_TENANT =
  "[NOTIFICATIONS] SWITCH_STATE_NOTIFICATION_BY_TENANT";
export const SWITCH_STATE_NOTIFICATION = "[NOTIFICATIONS] SWITCH_STATE_NOTIFICATION";
export const UPDATE_DATA_PAYMENTS = "[NOTIFICATIONS] UPDATE_DATA_PAYMENTS";
export const UPDATE_COUNT_NOTIFICATIONS = "[NOTIFICATIONS] UPDATE_COUNT_NOTIFICATIONS";
