// eslint-disable-next-line import/prefer-default-export
export const SET_PAYMENT_GATEWAY = "[PAYMENT_GATEWAY] SET_PAYMENT_GATEWAY";
export const CHANGE_STATUS_PAYMENT_GATEWAY = "[PAYMENT_GATEWAY] CHANGE_STATUS_PAYMENT_GATEWAY";
export const DELETE_PAYMENT_GATEWAY = "[PAYMENT_GATEWAY] DELETE_PAYMENT_GATEWAY";
