// eslint-disable-next-line import/prefer-default-export
export const SET_DATA_ECONOMIC_ACTIVITIES =
  "[ECONOMIC_ACTIVITIES_TYPES] SET_DATA_ECONOMIC_ACTIVITIES_TYPES";
export const SET_DATA_ECONOMIC_ACTIVITIES_CODE =
  "[ECONOMIC_ACTIVITIES_CODE_TYPES] SET_DATA_ECONOMIC_ACTIVITIES_CODE_TYPES";
