export const SET_DATA_SERVICE_STRATEGY_TYPES =
  "[SERVICE_STRATEGY_TYPES] SET_DATA_SERVICE_STRATEGY_TYPES";
export const SET_DATA_SERVICE_STRATEGY_CODE_TYPES =
  "[SERVICE_STRATEGY_TYPES] SET_DATA_SERVICE_STRATEGY_CODE_TYPES";
