export const SET_DATA_PROFILE = "[PROFILE_TYPES] SET_DATA_PROFILE";
export const UPDATE_DATA_PROFILE = "[PROFILE_TYPES] UPDATE_DATA_PROFILE";
export const RESET_DATA_PROFILE = "[PROFILE_TYPES] RESET_DATA_PROFILE";
export const CHANGE_LOADING_PROFILE = "[PROFILE_TYPES] CHANGE_LOADING_PROFILE";
export const CHANGE_LOADING_PROFILE_PASSWORD = "[PROFILE_TYPES] CHANGE_LOADING_PROFILE_PASSWORD";
export const CHANGE_LOADING_PROFILE_IMAGE = "[PROFILE_TYPES] CHANGE_LOADING_PROFILE_IMAGE";
